@startwbs
* Руководитель отдела\nДелаклуа Сидр Сидорович
** Руководитель команды качества\nВитон Сергей Петрович
*** ...
** Руководитель группы разработки\nнизкоуровневых алгоритмов и библиотек\nАнтуанеску Анатолий Александрович
*** ...
** Руководитель группы разработки\nприкладных програм\nХипстер Клауд Сергеевич
*** Руководитель группы разработки\nпрограм пеленгации спутников\n???
*** Руководитель группы разработки\nпрограм пеленгации наземных источников\nДупел Михаил Михайлович
*** ...
** Руководитель группы\nтехнических писателей\nЛивенгстон Авдотья Ивановна
*** ...
@endwbs