@startwbs
* Руководитель отдела\nДелаклуа Сидр Сидорович
** Руководитель команды качества\nВитон Сергей Петрович
*** ...
** Руководитель группы разработки\nнизкоуровневых алгоритмов и библиотек\nАнтуанеску Анатолий Александрович
*** ...
** Руководитель группы разработки\nприкладных програм\nХипстер Клауд Сергеевич
*** Руководитель группы разработки\nпрограм пеленгации спутников\n???
**** Старший разработчик\nДверь Петр Петрович
**** Старший разработчик\nНикасикуас Антона Петровича
**** Разработчик\nКлиппер Людмила Григорьевна
**** Разработчик\nЛианель Иван Сидорович
*** Руководитель группы разработки\nпрограм пеленгации наземных источников\nДупел Михаил Михайлович
**** Старший разработчик\nПропил Павел Евгеньевич
**** Разработчик\nВчера Анна Петровна
**** Разработчик\nКлю Тимур Иванович
*** ...
** Руководитель группы\nтехнических писателей\nЛивенгстон Авдотья Ивановна
*** ...
@endwbs